# === Run workflow on every push to main branch
on:
  push:
    branches: [ main ]

# === Define environment variables for the workflow ===
env:
  GODOT_VERSION: 4.6.1-stable

# === Define the job to export the game and create a release ===
jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    name: Export Game
    steps:

    # === Checkout the repository ===
      - name: checkout
        uses: actions/checkout@v5

    # === Export the game using firebelley/godot-export action ===
      - name: export game
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
            godot_executable_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}_linux.x86_64.zip
            godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}_export_templates.tpz
            relative_project_path: ./
            archive_output: true

    # === Create Tag ===
      - name: Create Tag
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          TAG="v${{ github.run_number }}"
          if ! git rev-parse "$TAG" >/dev/null 2>&1; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag "$TAG"
            git push origin "$TAG"
          fi

    # === Generate changelog ===
      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
            configuration: |
                template: |
                  ## Changes
                  {{CHANGELOG}}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # === Release Action ===
      - name: release
        uses: ncipollo/release-action@v1.18.0
        with:
            artifacts: ${{ steps.export.outputs.archive_directory }}/*
            tag: v${{ github.run_number }}
            name: Release v${{ github.run_number }}
            body: ${{ steps.changelog.outputs.changelog }}     
            token: ${{ secrets.GITHUB_TOKEN }}